version: "3"

networks:
  default:
    name: focumasy

services:
  db:
    image: postgres:bullseye
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  # app:
  #   build: .
  #   ports:
  #     - 3000:3000
